apiVersion: v1
kind: Service
metadata:
  name: imagebuilder
  labels:
    app: imagebuilder
spec:
  ports:
    - port: 3000
  selector:
    app: imagebuilder
  type: ClusterIP

---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: imagebuilder
  labels:
    app: imagebuilder
spec:
  selector:
    matchLabels:
      app: imagebuilder
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imagebuilder
    spec:
      containers:
      - image: 10.0.50.31:5000/dockerimagebuilder
        name: imagebuilder
        ports:
        - containerPort: 3000
          name: imagebuilder

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: builder-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: builder.auto.go.kr
    http:
      paths:
      - path: /
        backend:
          serviceName: imagebuilder
          servicePort: 3000
