dbConfig:
  redis:
    host: 10.0.50.25
    port: 6379
  remoteDocker:
    host: 10.0.50.25
    port: 2375
  dockerRegistry:
    host: registry.auto.go.kr
    port: 31365
  kubernetes:
    host: 10.0.50.31
    port: 6443
token:
  admin:
    value: 1dHUMcijIowiXpwJqPsbRZ8MUJxJzTut